/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>



// Registers

//RCC
#define RCC_BASE	   0x40021000
#define RCC_APB2ENR    *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN     (1<<2)
#define RCC_IOPBEN     (1<<3)

//GPIOA
#define GPIOA_BASE 			0x40010800
#define GPIOA_CRL			*(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH			*(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR			*(vuint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_ODR			*(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA13 			(1UL << 13)

//GPIOB
#define GPIOB_BASE 			0x40010C00
#define GPIOB_CRL			*(vuint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH			*(vuint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_IDR			*(vuint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_ODR			*(vuint32_t *)(GPIOB_BASE + 0x0C)
//#define GPIOB13 			(1UL << 13)

void clock_init(){
	// Enable clock for GPIOA and GPIOB
	RCC_APB2ENR |= RCC_IOPAEN;
	RCC_APB2ENR |= RCC_IOPBEN;
}

void GPIO_init(){
	// clear registers
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;

	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;

	GPIOA_ODR = 0x0;
	//PA1 input>> floating  >> MODE1 00 CNF1 01
	GPIOA_CRL |= (0b0100 << 4);
	//PA13 input>> floating   >> MODE13: 00 CNF13: 01
	GPIOA_CRH |= (0b0100 << 20);
	//PB1 output push-pull	  >> MODE1: 01(10Hz) CNF1: 00
	GPIOB_CRL |= (0b0001 << 4);
	//PB13 output push-pull  >> MODE13: 01(10Hz) CNF13: 00
	GPIOB_CRH |= (0b0001 << 20);
}

void wait_ms(uint32_t time){
	uint32_t i , j ;
	for(i = 0 ; i < time ; i++)
		for(j = 0 ; j < time ; j++);
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1){

		// PA1 (single press)
		if( (( GPIOA_IDR & (1 << 1)) >> 1 )  ==  0 ){

			GPIOB_ODR ^= (1<<1);
			wait_ms(100);
			while( (( GPIOA_IDR & (1 << 1)) >> 1 )  ==  0 ); // if we press p1 program will stop until not pressing it
		}
		//PA13 (multi press)
		if( (( GPIOA_IDR & (1 << 13)) >> 13 )  ==  1 ){

			GPIOB_ODR ^= 1<<13;
			wait_ms(100);

		}
		wait_ms(10);
	}
}
