/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include"stdio.h"
#include "../platform.h"

// REG definition

//typedef struct {
//	uint32 RCC_CR;
//	uint32 RCC_CFGR;
//	uint32 RCC_CIR;
//	uint32 RCC_APB2RSTR;
//	uint32 RCC_APB1RSTR;
//	uint32 RCC_AHBENR;
//	uint32 RCC_APB2ENR;
//	uint32 RCC_APB1ENR;
//	uint32 RCC_BDCR;
//	uint32 RCC_CSR;
//}RCC_REG_t;
//
//struct RCC_CFGR_R{
//	unit32 SW:2;
//	unit32 SWS:2;
//	unit32 HPRE:4;
//	unit32 PPRE1:3;
//	unit32 PPRE2:3;
//	unit32 ADCPRE:2;
//	unit32 PLLSRC:1;
//	unit32 PLLXTPRE:1;
//	unit32 PLLMUL:4;
//	unit32 USBPRE:1;
//	unit32 MCO:3;
//	unit32 RESERVED:5;
//
//};


#define RCC_BASE				  0x40021000
#define GPIOA_BASE	 			  0x40010800

#define RCC_CFGR     *((vuint32 *) (RCC_BASE + 0x04))
#define RCC_APB2ENR     *((vuint32 *) (RCC_BASE + 0x18))
#define RCC_CR     *((vuint32 *) (RCC_BASE + 0x00))


#define GPIOA_CRH	    *((vuint32 *) (GPIOA_BASE + 0x04))
#define GPIOA_ODR	    *((vuint32 *) (GPIOA_BASE + 0x0c))

#define RCC_IOPAEN (1<<2)  // pin2 in APB2ENR_reg in RCC (iopaen_bit)

typedef union {
	vuint32 PORTA;
	struct{
		vuint32  reserved:13;
		vuint32  A13:1;
	}pin;
}R_ODR_t;

volatile R_ODR_t*   R_ODR =  (volatile R_ODR_t*) (GPIOA_BASE + 0x0c);

int main(void)
{


	//	SW 0:1 System clock switch
	//	Set and cleared by software to select SYSCLK source.
	//	Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of
	//	failure of the HSE oscillator used directly or indirectly as system clock (if the Clock Security
	//			System is enabled).
	//			00: HSI selected as system clock
	//			01: HSE selected as system clock
	//			10: PLL selected as system clock
	//			11: not allowed
	RCC_CFGR |= (0b10 << 0);


	//	Bits 21:18 PLLMUL: PLL multiplication factor
	//	These bits are written by software to define the PLL multiplication factor. These bits can be
	//	written only when PLL is disabled.
	//	Caution: The PLL output frequency must not exceed 72 MHz.
	//		0000: PLL input clock x 2
	//		0001: PLL input clock x 3
	//		0010: PLL input clock x 4
	//		0011: PLL input clock x 5
	//		0100: PLL input clock x 6
	//		0101: PLL input clock x 7
	//		0110: PLL input clock x 8

	RCC_CFGR |= (0b0110 << 18);

	//	Bit 16 PLLSRC: PLL entry clock source
	//	Set and cleared by software to select PLL clock source. This bit can be written only when
	//	PLL is disabled.
	//		0: HSI oscillator clock / 2 selected as PLL input clock
	//		1: HSE oscillator clock selected as PLL input clock

	//RCC_CFGR &= (0b0<<16);

	//	Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	//	Set and cleared by software to control the division factor of the APB high-speed clock
	//	(PCLK2).
	//		0xx: HCLK not divided
	//		100: HCLK divided by 2
	//		101: HCLK divided by 4
	//		110: HCLK divided by 8
	//		111: HCLK divided by 16
	RCC_CFGR |= (0b101 << 11);

	//	Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	//	Set and cleared by software to control the division factor of the APB low-speed clock
	//	(PCLK1).
	//	Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
	//		0xx: HCLK not divided
	//		100: HCLK divided by 2
	//		101: HCLK divided by 4
	//		110: HCLK divided by 8
	//		111: HCLK divided by 16

	RCC_CFGR |= (0b100 << 8);

	//	Bits 7:4 HPRE: AHB prescaler
	//	Set and cleared by software to control the division factor of the AHB clock.
	//		0xxx: SYSCLK not divided
	//		1000: SYSCLK divided by 2
	//		1001: SYSCLK divided by 4
	//		1010: SYSCLK divided by 8
	//		1011: SYSCLK divided by 16
	//		1100: SYSCLK divided by 64
	//		1101: SYSCLK divided by 128
	//		1110: SYSCLK divided by 256
	//		1111: SYSCLK divided by 512

	RCC_CFGR |= (0b0000 << 4);

	 // RCC_CR
		//	Bit 24 PLLON: PLL enable
		//	Set and cleared by software to enable PLL.
		//	Cleared by hardware when entering Stop or Standby mode. This bit can not be reset if the
		//	PLL clock is used as system clock or is selected to become the system clock.
		//		0: PLL OFF
		//		1: PLL ON

		RCC_CR |= 1 << 24;


	RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH &= 0xFE0FFFFF; // to clear bits from (20 to 24)
	GPIOA_CRH |= 0x00200000;  //(mode=2)bit(20 to 24)

	while(1){
		R_ODR->pin.A13 = 1;
		for(int i=0;i<5000;i++);
		R_ODR->pin.A13 = 0;
		for(int i=0;i<5000;i++);
	}

}

