/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../stm32f103c6_Drivers/Inc/stm32f103c6.h"
#include "../stm32f103c6_Drivers/Inc/stm32f103c6_GPIO_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void Clock_init(){
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;

}

void GPIO_Init(){
	// Create configuration structure
	GPIO_PinConfig_t PinConfig;

	// Config PA1 as INPUT Floating
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;

	MCAL_GPIO_Init(GPIOA, &PinConfig);

	// Config PA13 as INPUT Floating
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;

	MCAL_GPIO_Init(GPIOA, &PinConfig);

	// config PB1 as output Push-Pull
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;

	MCAL_GPIO_Init(GPIOB, &PinConfig);
	// config PB13 as OUTPUT Open drain

	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_OD;
	PinConfig.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinConfig);

	return;


}

int main(void)
{
	Clock_init();
	GPIO_Init();
	while(1){
		// single press
		if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)) == 0){

			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);

			while((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)) == 0);

		}
		// multi pressing

		if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13)) == 0){

			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
			for(uint8_t i=0;i<254;i++);
		}

	}
}
