/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "../stm32f103c6_Drivers/Inc/stm32f103c6.h"
#include "../stm32f103c6_Drivers/Inc/stm32f103c6_GPIO_Driver.h"
#include "../stm32f103c6_Drivers/Inc/stm32f103c6_EXTI.h"
#include "../HAL/LCD/LCD.h"

uint8_t IRQ_Flag ;
void EXTI9_Callback(){
	IRQ_Flag = 1;

	HAL_LCD_Send_str("IRQ EXTI9 is happened (_|-)");
	Delay_ms(1000);
}


void Clock_init(){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}


int main(void)
{
	Clock_init();
	HAL_LCD_Init();
	EXTI_PinConfig_t EXTI_Config;
	EXTI_Config.EXTI_PIN =EXTI9PB9;
	EXTI_Config.Trigger_Case = EXTI_Trigger_RISINGAndFALLING;
	EXTI_Config.Ptr_IRQ_CallBack = EXTI9_Callback;
	EXTI_Config.IRQ_EN = EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);


	while(1){
		if(IRQ_Flag){
		HAL_LCD_Clear_Screen();
		IRQ_Flag=0;
		}
	}
}
