/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//======================================================
// Includes
//======================================================
#include "../stm32f103c6_Drivers/Inc/stm32f103c6_GPIO_Driver.h"
#include "../stm32f103c6_Drivers/Inc/stm32f103c6_USART.h"


void Clock_Init(void){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	RCC_AFIO_CLK_EN();

}



uint16_t	ch;
int main(void)
{
	USART_PinConfig_t	USART_PinConfig;
	//
	USART_PinConfig.USART_Mode =USART_Mode_TX_RX;
	USART_PinConfig.USART_Baudrate=USART_Baudrate_115200;
	USART_PinConfig.USART_Payload_Length=USART_Payload_Length_8bits;
	USART_PinConfig.USART_Parity=USART_Parity_None;
	USART_PinConfig.USART_StopBits=USART_StopBits_1;
	USART_PinConfig.USART_HWFlowCtrl=USART_HWFlowCtrl_None;
	USART_PinConfig.IRQ_EN=USART_IRQ_Enable_None;
	USART_PinConfig.Ptr_IRQ_CallBack=NULL;


	Clock_Init();
	//MCAL_GPIO_Init(GPIOA, PinConfig)
	MCAL_USART_Init(USART1, &USART_PinConfig);
	MCAL_USART_GPIO_Set_Pins(USART1);
	while(1){
		MCAL_USART_Receive(USART1, &ch, Enable);
		MCAL_USART_Send(USART1, &ch, Enable);


	}
}
